application: blog-udacity-br
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /stylesheets
  static_dir: stylesheets

- url: /.*
  script: lesson3.app

libraries:
- name: jinja2
  version: latest
